goadesign/goa.design

- layouts/section/design.html
- layouts/section/extend.html
- layouts/section/implement.html
These are 404ing as they use the wrong path, e.g. http://goa.design/extend/extend/gorma is shown on http://goa.design/extend/
The links on http://goa.design/learn/ are fine.
I use a modified version of golang docs' [linkcheck](https://golang.org/misc/linkcheck/linkcheck.go) to check links on all PRs for docs.rightscale.com, it's pretty quick and catches these types of issues by failing the build. It can also check external links. It's probably overkill for goa.design though...
> Fix top-level links

- content/design/vendoring.md
goagen/codegen/workspace.go uses astutil
This should be added to the dependency
> Add astutil dependency to glide.yaml

- content/learn/cellar.md
- content/learn/guide.md
make hosted cellar url unclickable (405 Method Not Allowed)
fix link to cellar from guide
> fix links in learn pages

- content/learn/guide.md
The current guide fails to install goa library and goagen binary on new Go installs.
```
root@ec1fd9887c93:/go# echo $PATH
/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@ec1fd9887c93:/go# echo $GOPATH
/go
root@ec1fd9887c93:/go# ls -l $GOPATH/src/
total 0
root@ec1fd9887c93:/go# go install github.com/goadesign/goa
can't load package: package github.com/goadesign/goa: cannot find package "github.com/goadesign/goa" in any of:
/usr/local/go/src/github.com/goadesign/goa (from $GOROOT)
/go/src/github.com/goadesign/goa (from $GOPATH)
root@ec1fd9887c93:/go# go install github.com/goadesign/goa/goagen
can't load package: package github.com/goadesign/goa/goagen: cannot find package "github.com/goadesign/goa/goagen" in any of: …
```
> Guide to go get recursively and minor typo

- Makefile
- content/extend/generators.md
Hey guys. When looking into the generator I noticed what I think were a couple of small errors in the example. I have updated it here.
I did the make command locally and served up the changes. The markdown with language definitions wasn't rendering correctly not sure why.
One other small thing I added github.com/goadesign/gorma to the makefile as it seems to be needed. The issue can be reproduced by removing the gorma line from the makefile. It results in the following error
```
could not find package github.com/goadesign/gorma in /Users/craigbrookes/servicesmake: *** [docs] Error 255
```
adding in the dependency solves this problem
> Example update for generator and bug fix in makefile dependencies

- content/implement/error_handling.md
`b` is out of scope when `return ctx.OK(b)`
> fix that the 'if' scope captures a variable

- content/blog/003-v1_1_0.ja.md
- content/blog/003-v1_1_0.md
Found myself in the blogpost surprisingly and the link was pointing to the non-existing target :).
> Tiny fix of url typo in the latest blog post.

- content/design/reference.ja.md
- content/design/reference.md
The page doesn't have content, it exists to make an entry in the top
menu but the page can be accessed from other ways, like directly typing
the URL or clicking the next page link present in "design/vendoring"
content page.
> design/reference: make it a placeholder for menu

- content/implement/context.md
I found an invalid link for the built-in timeout middleware and fixed it.
> Fix a invalid link

- layouts/partials/en/header.html
- layouts/partials/ja/header.html
For example, `<title>` of https://goa.design/learn/intro/.
```
goa :: Design-first API Generation
```
```
Introduction to goa · goa :: Design-first API Generation
```
> Show title for each page

- content/implement/goagen.md
Description of workaround when goagen is deleting .svn directories of Subversion < 1.7, as described in https://github.com/goadesign/goa/issues/1454
> Deleted .svn directories of Subversion workaround

- content/design/overview.md
- content/learn/getting-started.md
Fixing a wrong relative path in the examples for v3. 
Considering the user will be in the root of source code when running `go build ./cmd/calc` and `./calc`, the relative path for serving openapi.json should be `./gen/http/openapi.json`.
> Fixing relative path for openapi.json

- Makefile
It perhaps needs to set the parameters of go get according to the mod support situation for each library.
|dependencies|mod|
|:---|:---|
|gorma| not support|
|hugo|support|
> Fix getting dependencies with go get

- content/design/overview.ja.md
I removed remaining english sentence below.
> Body 関数はレスポンスボディからロードされる値を定義します。 loaded from the response body.
The page is [here](https://goa.design/ja/design/overview/#%E7%B5%90%E6%9E%9C%E3%81%8B%E3%82%89%E3%83%AC%E3%82%B9%E3%83%9D%E3%83%B3%E3%82%B9%E3%81%B8%E3%81%AE%E3%83%9E%E3%83%83%E3%83%94%E3%83%B3%E3%82%B0).
> Remove remaining english sentence

- .github/workflows/publish.yml
to avoid 'Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable'
> Define global GITHUB_TOKEN env var

- .gitignore
- content/design/overview.it.md
- content/design/overview.ja.md
- content/design/overview.md
- content/extend/plugins.it.md
- content/extend/plugins.ja.md
- content/extend/plugins.md
- content/implement/implementing.it.md
- content/implement/implementing.ja.md
- content/implement/implementing.md
- content/learn/getting-started.it.md
- content/learn/getting-started.ja.md
- content/learn/getting-started.md
The function name `Add` can be quite confusing for someone just starting with the project as it could taken the wrong way. For example:
AddEndpoint represents the endpoint for a method that adds two numbers, but it reads as though it adds a new endpoint to the server.
Altering to do multiplication seems like a word that would cause less confusion. I updated all references to Add/add to Multiply/multiply.
I'm not sure if there is anything in the non-English files that would need additional updating based on this wording change.
Great project!
> change Add to Multiply to avoid confusion

- content/blog/002-endpoints.it.md
- content/blog/002-endpoints.ja.md
- content/blog/002-endpoints.md
- content/design/handling_errors.it.md
- content/design/handling_errors.ja.md
- content/design/handling_errors.md
- content/design/overview.it.md
- content/design/overview.ja.md
- content/design/overview.md
- content/extend/plugins.it.md
- content/extend/plugins.ja.md
- content/extend/plugins.md
- content/implement/encoding.it.md
- content/implement/encoding.ja.md
- content/implement/encoding.md
- content/implement/middleware.it.md
- content/implement/middleware.ja.md
- content/implement/middleware.md
- content/implement/streaming.it.md
- content/implement/streaming.ja.md
- content/implement/streaming.md
- content/learn/getting-started.it.md
- content/learn/getting-started.ja.md
- content/learn/getting-started.md
- content/learn/upgrading.it.md
- content/learn/upgrading.ja.md
- content/learn/upgrading.md
- layouts/partials/en/navigation.html
- layouts/partials/it/navigation.html
- layouts/partials/ja/navigation.html
This pull request updates the existing GoDoc links in our documentation. Currently, these links point to the v2 documentation. This update modifies them to direct users to the more recent v3 GoDoc pages. This change ensures that users accessing the documentation are directed to the latest and most relevant information.
> chore: Change the GoDoc link to v3

- layouts/index.ja.html
"内臓" and "内蔵" look similar but have completely different meanings in Japanese.
- 内臓: visceral organ; viscus; viscera
- 内蔵: built-in
In this case, we should use "内蔵"; the original English sentence is "Built-in Best Practice".
-----
[内臓](https://ja.wikipedia.org/w/index.php?title=%E5%86%85%E8%87%93&redirect=no) は胃、腸、肝臓などの臓器を表す単語です。
一方、[内蔵](https://ja.wikipedia.org/wiki/%E5%86%85%E8%94%B5) は「あるものが内部に別のものを納め持っていること」です。
原文は"Built-in"なので、対応する訳語としては「内蔵」のほうが適切です。
> fix typo of 内蔵

- README.md
- package-lock.json
It turns out, that `make prereqs` wants to install a `hugo` release that won't work with the suggested `golang:1.21.2` version. It requires at least go 1.23.
This also clarifies the instructions of the README.md file, that the dockerized run requires nodejs.
Since we only need nodejs and npm, installing the versions that debian provides is a very slow process. So we mitigate this by using the nodejs version from nodejs.org.
> fixed prereqs dependencies

- Makefile
- README.md
`hugo` will bind - default - to localhost. When running in docker, we need to bind to any address or the development server won't be available to the exported port.
The Makefile will keep the default bind to `localhost` to keep the default security.
> fix the hugo bind address to run in docker

- content/en/docs/5-real-world/4-security/4-oauth2.md
The Real World > Security > Next Steps links are busted.  This PR fixes them.
Page:  (https://www.goa.design/docs/5-real-world/4-security/4-oauth2/)
> fix: busted links for security>oauth2>next steps

- assets/scss/_styles_project.scss
This Pull Request addresses the responsive layout issues reported in #175.
**Problem:**
The documentation site previously exhibited horizontal overflow on desktop and content clipping on mobile, leading to a suboptimal user experience where content was not properly contained within the viewport.
**Solution:**
This PR implements adjustments to the `width` properties of key layout elements and refactors some existing CSS to ensure content fits correctly within the screen, improving responsiveness across devices. Specifically:
* The widths of the left sidebar (`.td-sidebar`), the right sidebar / Table of Contents (`.td-sidebar-toc`), and the main content area (`.container-fluid`) have been adjusted.
* The problematic CSS rule `".container, .container-fluid {"` was removed from the styling, …
> Fix #175: Responsive layout - Address horizontal overflow and clipping
