content/design/overview.md
content/extend/plugins.md
content/implement/components.md
content/implement/context.md
content/implement/goagen.md
content/implement/middleware.md
content/implement/overview.md
content/learn/cellar.md
content/learn/guide.md

This is in reference to issue #277 defined at https://github.com/goadesign/goa/issues/277. I've made a number of changes to (most) of the markdown files. The changes were mostly just spelling mistakes, and a few little issues around grammar.

Review spelling and grammar

---

content/design/overview.md

As I kick the tires and learn about `goa` I discovered some broken links and tried to repair them.
I'm still very new to goa. It's possible I repaired a link by pointing to the wrong destination. Please verify.
Thanks,
-A

Repaired broken reference links

---

content/implement/goagen.md

Remove removed arguments from gen_client doc

---

content/design/overview.md
content/design/swagger.md
content/design/types.md

Updating documentation for the new datatype. goadesign/goa#441

Add uuid documentation, and fix typos.

---

content/extend/gorma.md

Reverts goadesign/goa.design#26

Revert "[DO NOT MERGE] Add docs describing the EntryPoint interface for a Store"

---

content/design/vendoring.md

Added code-based generation and vendoring section to `vendoring.md`

---

layouts/partials/navigation.html
static/css/style.css
static/css/style.less

Make easy to find the Reference (now with title and in bold) and Github links on the web page.
Having some text inside the links will make sure that those two links are show on mobile devices (right now, no links to /reference and the github page are shown in the navigation on mobile devices because they contain no text.)

Make easy to identify important links

---

content/extend/dsls.md

Signed-of-by Jeroen Simonetti <jeroen@simonetti.nl>

Tiny type fix

---

content/ja/intro.md
layouts/ja/single.html
layouts/partials/ja/footer.html
layouts/partials/ja/navigation.html
layouts/partials/navigation.html
layouts/section/ja.html

goa is an amazing library but it is not very popular in Japan at this point.
I would like to introduce goa to more Japanese people so I translate goa.design into Japanese.
This is an initial pull request so it includes only a few parts.
- index
- header
- footer
I will work on another parts if you like it.
Thank you.

Translate into Japanese

---

content/design/overview.md

Without the Headers i get an error `invalid use of Attribute in response "created"`

ResponseTemplate needs a extra Headers compound

---

config.toml
layouts/partials/footer.html

This is related to https://github.com/goadesign/goa.design/pull/45#issuecomment-258196098.

Improve language selection

---

content/design/vendoring.md

Hi,
This updates docs to use constructor methods.
Thank you.

Updates vendoring example to use generator constructor methods

---

content/design/vendoring.md

This is an updating related to https://github.com/goadesign/goa/pull/1050.

Update behavior of goagen

---

content/implement/goagen.md

https://github.com/goadesign/goa/pull/1284#issuecomment-311802954

Update the behavior of gen_controller --pkg

---

content/implement/middleware.md

The security page however is blank.

Fix some broken links

---

content/learn/getting-started.md

See https://github.com/goadesign/goa/issues/2107

Address Goa issue #2107

---

content/design/overview.md

Insert line break

---

content/design/handling_errors.md

Numbered list doesn't work here, so I think it is better to use bullet list.

Use bullet list instead of numbered list

---

content/learn/getting-started.md

Just added missing 'see' word in sentence
> As you can Goa accelerates service development by making it possible to write
the single source of truth from which server and client code as well as
documentation is automatically generated.

Fix missing 'see' word.

---

content/implement/error_handling.md

Tweak error docs.

---

content/implement/error_handling.md

Additional tweaks to the error docs

Additional tweaks to the error docs

---

content/extend/plugins.md

While reading documentation I found an extra word that made the sentence awkward.

Removed extra word

---

content/implement/implementing.ja.md

#125
https://github.com/goadesign/goa.design/pull/128#issuecomment-1010630663
Would you review this? @ikawaha

Translate title in implement/implementing into ja

---

.github/workflows/publish.yml

When building site as SCSS requires it.

Use extended version of Hugo

---

content/en/docs/6-advanced/5-sticky-cookies.md
content/en/docs/6-advanced/_index.md

Added a documentation section for sticky cookies when using horizontal scaling of services with websockets.

sticky cookies documentation

---

content/en/docs/5-real-world/2-observability/4-logging.md

This helps debugging using Promtail, Loki, Grafana and Prometheus on a Kubernetes Cluster.
It might save tons of hours of trial and error I had.

added Promtail / Grafana / Loki hint
